name = "ghost-buster-bot"
main = "src/worker.ts"
compatibility_date = "2024-08-01"
compatibility_flags = ["nodejs_compat"]
account_id = "b480d5f28dce910419458a20d2656fbe"

[vars]
# Set via `wrangler secret put TELEGRAM_BOT_TOKEN`
# Set via `wrangler secret put TELEGRAM_WEBHOOK_SECRET`
[triggers]
crons = ["0 7 * * *"]

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "ghost-buster-bot"
database_id = "1afc51cd-0b8c-4304-9b3e-6f062980959c"

