name = "ghost-buster-bot"
main = "src/worker.ts"
compatibility_date = "2024-08-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# Set via `wrangler secrets put TELEGRAM_BOT_TOKEN`
# Set via `wrangler secrets put TELEGRAM_WEBHOOK_SECRET`

[[d1_databases]]
binding = "DB"
database_name = "ghost-buster-bot"
database_id = "ghost-buster-bot"

[triggers]
crons = ["0 5 * * *"]

